
apimServiceName: apim-prod-wk-05102022
namedValues:
  - name: environment
    displayName: environment
    value: "https://www.search.com"
  - name: mysecretvalue
    displayName: mysecretvalue
    keyVault:
      identityClientId: f5cf4186-20c1-4e5b-abbf-abd174bee744
      secretIdentifier: https://secretvaultwk.vault.azure.net/secrets/mysecretvalueprod
  - name: testSecret
    displayName: testSecret
    value: "{#testSecretValue#}"
loggers:
    - name: apim-lab-insights
      loggerType: applicationInsights
      description: prod application insights
      resourceId: "/subscriptions/77fadbdc-74f1-4ce8-8962-b34400a1f170/resourceGroups/
                   rg-apim-lab-prod/providers/microsoft.insights/components/apim-lab-prod-insights"
      credentials:
        instrumentationKey: "{{Logger-Credentials--62825ade46346113589affc1}}"
        isBuffered: true
diagnostics:
   - name: applicationinsights
     verbosity: Error
     loggerId: "/subscriptions/77fadbdc-74f1-4ce8-8962-b34400a1f170/resourceGroups/rg-apim-lab-prod/providers/Microsoft.ApiManagement/service/apim-prod-wk-05102022/loggers/apim-lab-prod-insights" 
apis:
  - name: demo-conference-api
    diagnostics:
      - name: applicationinsights
        verbosity: Error
        loggerId: "/subscriptions/77fadbdc-74f1-4ce8-8962-b34400a1f170/resourceGroups/rg-apim-lab-prod/providers/Microsoft.ApiManagement/service/apim-prod-wk-05102022/loggers/apim-lab-prod-insights"
