openapi: 3.0.1
info:
  title: helloworldfromfuncapp
  description: Import from "helloworldfromfuncapp" Function App
  version: '1.0'
servers:
  - url: https://api.waelsconsulting.com/helloworldfromfuncapp
  - url: https://portal.waelsconsulting.com/helloworldfromfuncapp
paths:
  /HttpTrigger1:
    post:
      summary: HttpTrigger1
      description: HttpTrigger1
      operationId: post-httptrigger1
      responses:
        '200':
          description: ''
    get:
      summary: HttpTrigger1
      description: HttpTrigger1
      operationId: get-httptrigger1
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]