openapi: 3.0.1
info:
  title: myversionedapi
  description: ''
  version: ''
servers:
  - url: https://api.waelsconsulting.com/myversionedapi
  - url: https://portal.waelsconsulting.com/myversionedapi
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]