openapi: 3.0.1
info:
  title: helloworldfromlogicapp
  description: Azure Logic App.
  version: '1.0'
servers:
  - url: https://api.waelsconsulting.com/helloworldfromlogicapp
  - url: https://portal.waelsconsulting.com/helloworldfromlogicapp
paths:
  /manual/paths/invoke:
    get:
      summary: manual-invoke
      description: Trigger a run of the logic app.
      operationId: manual-invoke
      requestBody:
        description: The request body.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/request-manual'
      responses:
        '200':
          description: The Logic App Response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManualPathsInvokeGet200ApplicationJsonResponse'
        '500':
          description: The Logic App Response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManualPathsInvokeGet500ApplicationJsonResponse'
components:
  schemas:
    request-manual: { }
    ManualPathsInvokeGet200ApplicationJsonResponse:
      type: object
    ManualPathsInvokeGet500ApplicationJsonResponse:
      type: object
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]