# This is a basic workflow to help you get started with Actions

name: Get APIOps Release

# Controls when the workflow will run
on:
   workflow_dispatch:
     inputs:
       Release_Version:
         description: 'Provide a release version. e.g. v.3.1.0'     
         required: true
         type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Fetch latest artifacts
        env:
          SourceCodeFile: apiopslab-${{ github.event.inputs.Release_Version}}
        run: |
          wget https://github.com/waelkdouh/apiopslab/archive/refs/tags/${{ github.event.inputs.Release_Version}}.zip
          unzip ${{ github.event.inputs.Release_Version}}.zip
          rm ${{ github.event.inputs.Release_Version}}.zip
          pwd
          #cp ${SourceCodeFile}/tools/github_workflows .github/workflows
          #cd .github/workflows
          ls
          

