# This is a basic workflow to help you get started with Actions

name: Generate_Github_Release_Binaries

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x
          include-prerelease: true

      - name: Publish Release Binaries
        run: |
          echo 'print content default directory'
          pwd
          ls
          #echo 'this is the content of the work/apiopslab/apiopslab directory'
          #ls /home/runner/work/apiopslab/apiopslab
          cd tools/code/extractor/
          dotnet publish ./extractor.csproj --self-contained --runtime linux-x64 -p:PublishSingleFile=true -o wael
          echo 'print content of the current directory'
          pwd
          ls
          #cd tools/code/extractor/wael
          #echo 'print content of wael'
          #pwd
          #ls
          
           
       #   #cd /home/runner/work/extractor
       #   echo 'print the contents of /home/runner'
       #   ls
       #   cd /home/runner/work
       #   echo 'print the contents of /home/runner/work
       #   ls
          #cp tools/code/extractor/extractor/* ${{github.workspace}}\release_binaries
          #cp  ${{github.workspace}}/configuration.prod.yaml ${{github.workspace}}/release_binaries
